
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 25 18:10:25 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 22;
  public static final int CONTINUE = 30;
  public static final int IDENT = 34;
  public static final int ELSE = 26;
  public static final int ASTERISK = 13;
  public static final int PERCENT = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 3;
  public static final int RPAREN = 6;
  public static final int EQUAL = 16;
  public static final int CHAR = 33;
  public static final int SEMI = 4;
  public static final int SLASH = 14;
  public static final int NAMESPACE = 20;
  public static final int DBLCOLON = 10;
  public static final int RETURN = 23;
  public static final int IF = 25;
  public static final int LPAREN = 5;
  public static final int LBRACKET = 7;
  public static final int LBRACE = 2;
  public static final int PROGRAM = 19;
  public static final int RBRACKET = 8;
  public static final int NUM = 31;
  public static final int INC = 17;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int BREAK = 29;
  public static final int DEC = 18;
  public static final int MINUS = 12;
  public static final int CONST = 27;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int NEW = 28;
  public static final int BOOL = 32;
  public static final int VOID = 24;
}

