
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 25 10:26:33 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 22;
  public static final int ELSE = 17;
  public static final int PLUS = 9;
  public static final int RBRACE = 3;
  public static final int RPAREN = 6;
  public static final int EQUAL = 10;
  public static final int CHAR = 21;
  public static final int SEMI = 4;
  public static final int DBLCOLON = 8;
  public static final int RETURN = 14;
  public static final int IF = 16;
  public static final int LPAREN = 5;
  public static final int LBRACE = 2;
  public static final int PROGRAM = 11;
  public static final int NUM = 19;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int NSP = 12;
  public static final int CONST = 18;
  public static final int PRINT = 13;
  public static final int error = 1;
  public static final int BOOL = 20;
  public static final int VOID = 15;
}

